/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.hyperskill.gradleapp
import kotlinx.datetime.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
	val tz1 = TimeZone.currentSystemDefault()
	println(tz1)
    println(App().greeting)
}
